# Generated by Django 5.2.6 on 2025-10-01 13:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lobby_lobbymembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('kettle', 'Чайник'), ('thermometer', 'Термометр'), ('lamp', 'Лампочка')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.lobby')),
            ],
        ),
    ]
