# Generated by Django 5.2.6 on 2025-10-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_active',
        ),
        migrations.AddField(
            model_name='device',
            name='access_roles',
            field=models.CharField(default='owner,admin,member', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('lamp', 'Лампочка'), ('kettle', 'Чайник'), ('thermometer', 'Термометр')], max_length=20),
        ),
    ]
