# Generated by Django 5.2.6 on 2025-10-01 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_device_is_active_device_access_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('kettle', 'Чайник'), ('thermometer', 'Термометр'), ('lamp', 'Лампочка')], max_length=20),
        ),
    ]
